### ISSUE TITLE
 TypeError: Cannot read property 'bounds' of undefined

### ISSUE THREAD

**Issue by redpeer** [macacajs/app-inspector#167] opened 2018-01-20 09:11 UTC
app-inspector: 2.0.10
uiautomator:1.0.45
xiaomi5手机 

 >> port: 5678 was occupied, changed port: 5680
>> server.js:16:12 [master] pid:12396 server start with config:
 { port: 5680,
  verbose: true,
  udid: '64d34e83',
  ip: '192.168.31.179',
  host: 'air.local',
  loaded_time: '2018-01-20 17:20:43' }
>> app-inspector.js:43:12 [master] pid:12396 server start at: http://192.168.31.179:5680
>> uiautomator-client.js:61:14 [master] pid:12396 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:61:14 [master] pid:12396 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9001<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> Android device started: 64d34e83
>> inspector start at: http://192.168.31.179:5680
  <-- GET /
>> proxy.js:55:14 [master] pid:12396 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:9001/wd/hub/session/:sessionId/source:GET with body: null
>> proxy.js:85:20 [master] pid:12396 Got response with status 200: {"status":0,"value":"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\r\n<hierarchy rotation=\"0\" />","sessionId":null}
>> Dump Android XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/android.json

  TypeError: Cannot read property 'bounds' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/android.js:28:14)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/android.js:49:14)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by tanfeiqi** [comment] 2018-10-24 09:04
me too 
app-inspector: 2.0.21
uiautomator:1.0.60
device: nubia Z11
how to solve it?

**Comment by paradite** [comment] 2019-02-24 08:56
I think the issue might have been fixed with https://github.com/macacajs/app-inspector/commit/c796b62b04a12de34477d4d2044eee38d78aa18d#diff-b550f6a6b3ec7ae4e9b136a8f55e3954R53
Re-open if it is not working as intended or you have any other related issues.

**Closed by paradite** 2019-02-24 08:56 UTC
